services:
  primary:
    image: percona/percona-server:8.0
    command: --server-id=1 --port=3306 --log_error_verbosity=3 --log-bin --log-replica-updates --gtid_mode=on --enforce-gtid-consistency --innodb_flush_log_at_trx_commit=2 --sync_binlog=0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - 3306:3306
    volumes:
      - ./init-primary.sql:/docker-entrypoint-initdb.d/init-primary.sql:ro
  replica:
    image: percona/percona-server:8.0
    command: --server-id=2 --port=3307 --log_error_verbosity=3 --log-bin --log-replica-updates --gtid_mode=on --enforce-gtid-consistency --innodb_flush_log_at_trx_commit=2 --sync_binlog=0 --read_only=ON --replica_parallel_workers=1
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - 3307:3307
    volumes:
      - ./init-replica.sql:/docker-entrypoint-initdb.d/init-replica.sql:ro
    depends_on:
      - primary
      - toxiproxy
  toxiproxy:
    image: ghcr.io/shopify/toxiproxy
    command: -host=0.0.0.0 -config /toxiproxy.json -proxy-metrics
    expose:
      - 3306
      - 8474
    ports:
      - 8474:8474
    volumes:
      - ./toxiproxy.json:/toxiproxy.json:ro
    depends_on:
      - primary
  test:
    build:
      dockerfile: Dockerfile
    depends_on:
      - primary
      - toxiproxy
